main.js
package.json

Implements Copy & Paste functionality. Closes #15 .

Allow copy & paste within the app

---

src/js/components/notification.js

Pull Request notifications had the URL: `https://www.github.com/atom/find-and-replace/pulls/399`
Which would link to an author. This PR corrects it to be: `https://www.github.com/atom/find-and-replace/pull/399`
I only had one notification to test it with though.

Correct URL for Pull Requests

---

main.js
package.json
src/js/__tests__/components/footer.js
src/js/__tests__/components/notifications.js
src/js/__tests__/components/search-input.js
src/js/__tests__/stores/search.js
src/js/actions/actions.js
src/js/components/footer.js
src/js/components/notifications.js
src/js/components/repository.js
src/js/components/search-input.js
src/js/stores/search.js
src/less/style.less

Add a search input to the bottom of the menu for easily filtering organisations and repositories.

Search notifications

---

package.json
src/js/__tests__/components/notification.js
src/js/__tests__/components/notifications.js
src/js/__tests__/components/settings.js
src/js/__tests__/stores/notifications.js
src/js/__tests__/stores/sound-notification.js
src/js/actions/actions.js
src/js/components/settings.js
src/js/stores/notifications.js
src/js/stores/settings.js
src/js/stores/sound-notification.js

Native Notifications

---

src/js/__tests__/components/notification.js
src/js/__tests__/components/repository.js
src/js/components/notification.js
src/js/components/repository.js
src/js/utils/api-requests.js
src/less/style.less

Mark Repository as Read

---

main.js
package.json
src/js/components/settings.js
src/js/stores/settings.js

Added "Open at startup" option

---

package.json
src/js/components/login.js

Update dist script & Remove client secret key

---

main.js

Hi.
Thank you for such a great app.
In OS X, gitify is now bound to specific work space where gitify firstly started.  When I click the menu icon in other workspace, the window will be opened in the bound work space and current workspace is forced to be changed.
I used `BrowserWindow.setVisibleOnAllWorkspaces()` API to solve this issue.
https://github.com/atom/electron/blob/master/docs/api/browser-window.md#browserwindowsetvisibleonallworkspacesvisible
I think all menu bar applications should set this option to true.

Make visible menu window on all workspaces

---

.eslintrc
main.js
package.json

Move to eslint

---

src/less/style.less

Smaller font size for repos names

---

README.md

The client id and secret are defined in constants.js, not login.js (although they are consumed there).

Additional clarity to Development section in README

---

src/js/__tests__/utils/notifications.js
src/js/components/notification.js
src/js/utils/helpers.js
src/js/utils/notifications.js

Closed #207 .
On click of a native notification, if there is only 1 notification, it will go straight to the browser. If there are multiple, it will open Gitify.

#207 - Click on notification(1) goes straight to GitHub

---

src/js/__tests__/actions/index.js
src/js/__tests__/reducers/settings.js
src/js/actions/index.js
src/js/components/login.js
src/js/components/notifications.js
src/js/middleware/requests.js
src/js/reducers/settings.js
src/js/store/configureStore.js
src/js/utils/constants.js

186 - Hide "Star on GitHub"

---

README.md
src/js/__tests__/components/network-status.js
src/js/__tests__/containers/app.js
src/js/components/network-status.js
src/js/containers/app.js
src/scss/app.scss

[209] Check Internet Connection

---

README.md
src/js/components/sidebar.tsx
src/js/routes/login.tsx
src/js/utils/helpers.test.ts
src/js/utils/helpers.ts

Thanks to @AlecRust suggestion in #304. Also fixes #317 .

Fix GitHub hostname - Avoid Redirects

---

src/js/__mocks__/electron.js
src/js/utils/helpers.test.ts
src/js/utils/helpers.ts

Clear the BrowserWindow session on login

---

package.json
src/js/__mocks__/mockedData.ts
src/js/__mocks__/redux-logger.js
src/js/components/sidebar.test.tsx
src/js/middleware/notifications.test.ts
src/js/routes/enterprise-login.test.tsx
src/js/routes/notifications.test.tsx
src/js/routes/settings.test.tsx
src/js/store/configureStore.ts
src/js/utils/__snapshots__/github-api.test.ts.snap
src/js/utils/comms.test.ts
src/js/utils/github-api.test.ts
src/js/utils/github-api.ts
yarn.lock

This raises the line-by-line test coverage from 98% to 100%. I tried to keep my edits limited to only the tests, with the exception of `src/js/store/configureStore.ts` having a block of code that looks like it exists for debugging/development.

Raise test coverage to 100%

---

package.json
src/js/components/notification.tsx
src/js/utils/helpers.ts
src/js/utils/notifications.ts

Fixes a console error borne of attempting to create a GitHub url when the `url` property of the `subject` returned with an individual thread in the Notifications thread in the url is not properly populated.
Also fixes a few missing types, but i can get rid of that if you'd prefer!
I've raised an issue with the Notifications team within GitHub about the missing urls, so some of them may end up fixed soon 🤞
cc @manosim

fix: only try to open links if non-null url

---

src/js/components/__snapshots__/notification.test.tsx.snap
src/js/components/notification.tsx

Adds a helpful tooltip for the green check to indicate its function a bit more clearly!
After:
As an aside, I love this app - thanks for working on it 🙇‍♀️

feat: add missing mark-read tooltip

---

src/js/actions/index.test.ts
src/js/actions/index.ts
src/js/components/__snapshots__/notification.test.tsx.snap
src/js/components/notification.test.tsx
src/js/components/notification.tsx
src/js/middleware/notifications.ts
src/js/reducers/notifications.ts

Closes https://github.com/manosim/gitify/issues/402.
When the new unsubscribe icon is clicked, all future notifications for a conversation are muted until one comments on the thread or gets an @mention.
cc @manosim

feat: enable unsubscribing notifications

---

src/js/actions/index.test.ts
src/js/actions/index.ts

As I used the new unsubscribe feature, I discovered an annoying little idiosyncrasy - the [set thread subscription](https://developer.github.com/v3/activity/notifications/#set-a-thread-subscription) endpoint encompasses more thorough functionality than the [delete thread subscription](https://developer.github.com/v3/activity/notifications/#delete-a-thread-subscription) endpoint.
Essentially - both endpoints can mute all future notifications for a conversation until you comment on the thread or get an @mention. _However_, the delete endpoint includes this caveat:
> If you are watching the repository of the thread, you will still receive notifications.
Which sort of nerfs a lot of the reasons one would unsubscribe from a notification in the first place. To unsubscribe regardless of watch …

fix: use thread subscription set endpoint

---

first-run.js
main.js
package.json
tsconfig.json

Closes https://github.com/manosim/gitify/issues/417.
When gitify first opens, it will now request to move itself to the Applications folder on macOS. The user's choice will be stored for subsequent runs. If it's _already_ in the Applications folder, no prompts are shown.
cc @manosim I pulled the functionality into a new file but if you'd prefer I can put it into `main.js` or do something else entirely with it, up to you!

feat: move to app folder on first run

---

src/js/utils/github-api.test.ts
src/js/utils/github-api.ts
src/types/github.ts

Adds missing icon data for GitHub Discussions.
Before:
After:
cc @manosim

fix: add missing Discussions data

---

src/js/utils/constants.tsx

Unfortunately this emoji has been used as a symbol of hate by some groups so it's probably best to remove it.

Remove ok hand emoji

---

first-run.js
main.js

Since we updated Electron, the `menubar` fails to handle the `showDockIcon` flag. This PR has a temporary workaround by calling `menubarApp.app.dock.hide()` when the window has been created.
See https://github.com/maxogden/menubar/issues/306 for more.

feat: Hide app's dock icon

---

main.js
package.json
yarn.lock

Call `app.dock.hide()` only if `hide()` exists.
Closes #451.

fix: Hide dock icon only for macOS

---

README.md

Fix error when installing using latest Homebrew. This is not a bug of this app, but readme needs to be fixed.
screenshot:

docs: Fix installation instructions in readme

---

auto_updater.json

This was used before v3 and since we've now moved to using `electron-updater`, we can now safely delete it.

chore: Remove previous auto-update config

---

src/components/Sidebar.test.tsx
src/components/Sidebar.tsx
src/components/__snapshots__/Sidebar.test.tsx.snap

Closes #435 .
Makes the badge with the notifications count a link to [github.com/notifications](github.com/notifications).
https://user-images.githubusercontent.com/6333409/103587146-82da8f80-4ede-11eb-8f63-3772d423bf62.mp4

feat: Add link to GitHub Notifications page

---

src/routes/LoginWithToken.tsx

GitHub has a [new token format](https://github.blog/2021-04-05-behind-githubs-new-authentication-token-formats/) which introduces `_` as an allowed character. 
Fixes #491

Add underscore to allowed characters for personal access tokens

---

main.js
src/routes/Settings.tsx

Closes https://github.com/manosim/gitify/issues/496.
Fixes an issue that could occur when the theme was set to `System`. In this case, if the user updated dark mode on their OS, the theme wouldn't update in the app unless it was quit and opened again. Fix this by using `nativeTheme` to listen for system theme changes and update the UI accordingly.

fix: dark mode not toggling with system

---

src/hooks/useNotifications.ts

Closes https://github.com/manosim/gitify/issues/421
The unsubscribe button isn't actually updating the subscription. From [here](https://docs.github.com/en/rest/reference/activity#set-a-thread-subscription) it appears the key should be `ignored` rather than `ignore` (even though [right below](https://docs.github.com/en/rest/reference/activity#delete-a-thread-subscription) mentions `ignore`).

fix: unsubscribe button ignoring thread subscription

---

package.json
src/components/AllRead.test.tsx
src/components/AllRead.tsx
src/components/__snapshots__/AllRead.test.tsx.snap
src/index.tsx
src/utils/constants.ts
yarn.lock

Remove all read messages

---

src/utils/auth.ts

Hi, @manosim 
Recently, Github OAuth redirect is changed by meta refresh tag, So it cannot capture auth code from callback url. I added `will-navigate` event capture function, it can help capture auth code from meta refresh tag and login Gitify.

Capture callback by `will-navigate` event

---

src/context/App.tsx
src/utils/auth.ts

Hello, @manosim 
@Uanid fix about Issue #502 to PR #504. But, it is outdated and have conflicts. Also, I think reusing `getUserData` is much better, so I add hostname parameter in `getUserData` method. What do you think about it?

Fix Personal Access Token login method to Github Enterprise Server modifying getUserData

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml

chore: create issue templates

---

src/components/Sidebar.test.tsx
src/components/Sidebar.tsx
src/components/__snapshots__/Sidebar.test.tsx.snap

Fixes what was discussed in #551 and closes #543.

feat: remove gh icon & keep notifications icon

---

src/routes/Settings.tsx

Changes the casing and phrasing of the "On Click, Mark as Read" label to "Mark as read on click".

Change casing and phrasing of `onClickMarkAsRead` field

---

.gitignore
src/context/App.tsx
src/hooks/useNotifications.ts
src/utils/auth.ts

Hello,
I saw #524, Also I tested with latest commits.
But Login to Github Enterprise Server with PAT not works. (See #527)
Because Github Etnerprise Server's API url pattern is `https://${hostname}/api/v3`.
This PR deduplicates api-url generate codes.
https://docs.github.com/en/enterprise-server@3.3/rest/reference/users

fix: github enterprise login

---

src/app.tsx

This is step #2 of upgrading to React Router v6. https://reactrouter.com/en/main/upgrading/v5#upgrade-to-react-router-v51
As reference, I looked at
https://reacttraining.com/blog/react-router-v5-1 and https://gist.github.com/mjackson/d54b40a094277b7afdd6b81f51a0393f

chore(routing): Switch to new react-router syntax

---

first-run.js

I'm not sure where this came from since `outputFileSync` comes from `fs-extra`... I guess it always failed?

fix: remove `outputFileSync` usage

---

.github/workflows/run-tests.yml

This change resolves #646 by modifying the .github/workflows/run-test file to just execute the test on the pull request not in the push. Before tests were executed twice. 
Signed-off-by: JoseAlberola

chore(CI): don't run tests twice per PR

---

jest.config.js
main.js
package.json
pnpm-lock.yaml
src/__mocks__/@electron/remote.js
src/__mocks__/electron.js
src/hooks/useNotifications.test.ts
src/routes/Settings.test.tsx
src/routes/Settings.tsx
src/utils/auth.test.ts
src/utils/auth.ts
src/utils/comms.test.ts
src/utils/comms.ts
src/utils/notifications.ts

This is [a requirement for electron v14, which drops the module](https://www.electronjs.org/blog/electron-14-0/#removed-remote-module). We can do it before the upgrade, for smaller changes.

chore(electron): Move off deprecated remote module

---

src/hooks/useNotifications.ts

Thanks to many contributions released in https://github.com/gitify-app/gitify/releases/tag/v4.4.0, almost issues related to GitHub Enterprise Server have been fixed.
However, an issue about token usage still remains.
* Fix to use an enterprise token if the notification's hostname is enterprise server's name.
* Current implementation used a github.com token for everything, so some API calls failed with a 401 error.

fix: use enterprise token if hostname of notification is enterprise server 

---

main.js
src/utils/comms.test.ts
src/utils/comms.ts

One of the last usages of remote, which generally isn't recommended

chore: Replace remote for setting auto-open pref

---

.github/workflows/trigger-homebrew.yml

Custom action was broken, so this PR replaces it with the official `bump-cask-pr` CLI, which can be seen working here: https://github.com/gitify-app/gitify/actions/runs/7108934623/job/19353060346

refactor: use brew CLI over custom action

---

src/components/fields/Checkbox.tsx
src/context/App.test.tsx
src/context/App.tsx
src/routes/Settings.test.tsx
src/routes/Settings.tsx
src/routes/__snapshots__/Settings.test.tsx.snap

Alternative to #660, also attempting to fix https://github.com/gitify-app/gitify/issues/624, since enabling colors for existing users is breaking notifications for those without the repo scope.
This PR notifies the user every time that he doesn't have the required scopes and disables colors in case he doesn't. Opted by not logging out to not be too annoying.
Warning: Implementation might not be the best.

feat: check for github scopes

---

.github/workflows/on-tag.yml

Create notice over pr so that there is no need for a PAT. In the future if we can get a fine grained token that would be better.
This is supposed to trigger a build so that Astro can fetch the new version, as this is still more performance than shipping Astro with something else to fetch the latest version on the client side as was tested in https://github.com/gitify-app/website/pull/33

chore: rename to `on-tag` and trigger web build

---

scripts/notarize.js

It should be straightforward for us, as per https://developer.apple.com/documentation/technotes/tn3147-migrating-to-the-latest-notarization-tool

fix(macos): switch from `altool` to `notarytool`

---

src/__mocks__/mock-state.ts
src/components/NotificationRow.test.tsx
src/components/NotificationRow.tsx
src/components/Sidebar.test.tsx
src/components/__snapshots__/NotificationRow.test.tsx.snap
src/context/App.test.tsx
src/context/App.tsx
src/routes/Settings.test.tsx
src/routes/Settings.tsx
src/routes/__snapshots__/Settings.test.tsx.snap
src/types.ts

refactor: remove now redundant `mark as read on click` functionality

---

package.json

Let's push this version even if we can't get it properly signed for macOS yet. I'll manually delete the release files for MacOS in the meantime so it doesn't create confusion.

chore: bump to `v4.6.1`

---

.github/workflows/build-app.yml
.github/workflows/on-tag.yml
.github/workflows/release.yml

According to https://twitter.com/yagiznizipli/status/1752740836461167041 and https://github.blog/changelog/2024-01-30-github-actions-macos-14-sonoma-is-now-available/ this should severely improve our macos runners performance.
Edit: Confirmed ✅  Went from ~4minutes to ~2m10s

chore: update runners to `macos-14`

---

src/components/NotificationRow.tsx
src/utils/github-api.test.ts
src/utils/github-api.ts

Make Gitify icons match Github icons
I had to pass the `state` parameter to `getNotificationTypeIcon` because I needed this context to find the correct icon. I made it optional because it felt more accurate.
I tried to find all different states/icons but I might be missing some; if so, I default to the original icon, so there shouldn't be any regression
Before:
After:

feat: better notification type icons

---

renovate.json

Configure Renovate to split multiple major release jumps into individual PRs, so that we can incrementally close the gap (eg: electron 22 -> 28).
Also enabled osv alerts for security related PRs

build(renovate): configuration updates for major versions and osv

---

src/components/NotificationRow.tsx
src/components/Repository.tsx
src/components/__snapshots__/NotificationRow.test.tsx.snap
src/components/__snapshots__/Repository.test.tsx.snap

As discussed here https://github.com/gitify-app/gitify/pull/745#issuecomment-1947439114
Make small changes to improve the UI/UX following the recent changes on icons
Changes made in this PR are:
- Move the `NotificationRow` "Mark as read" button to the right
- Reduce the "Mark repository as read" icon size and make it aligned with the `NotificationRow` icons
- Add missing `title` to the "Mark repository as read"
- Change some paddings to keep all elements aligned
- Change `NotificationRow` buttons size (they now take more height), and move the `hover:text-{color}-500` class to the button instead of the icon

feat: improve icons ui/ux

---

src/components/Repository.tsx
src/components/Sidebar.tsx
src/routes/LoginWithToken.tsx
src/utils/comms.test.ts
src/utils/comms.ts

feat: prevent local files from opening

---

src/components/NotificationRow.test.tsx
src/components/NotificationRow.tsx
src/context/App.tsx
src/hooks/useNotifications.test.ts
src/hooks/useNotifications.ts

- Fixes #785 
Remove notification from state when clicking on it.

fix: remove notification from state on open

---

src/context/App.test.tsx
src/context/App.tsx
src/hooks/useNotifications.ts
src/types.ts

- Fixes #786 
Show notification icons colors on app first load / app refresh.
I've identified 2 possible fixes:
- First one would be to simply drop this code so that we fetch the `state` of each notifications, even though `settings.colors` is falsy.
https://github.com/gitify-app/gitify/blob/1c3c248fd89299d519457ed1d7c3444ab6bf92c2/src/hooks/useNotifications.ts#L107-L117
Since `notification.state` is, for now, only required to load the icons colors, this would result on making a lot of unnecessary api calls if the setting is disabled.
- Second one is the one I've implemented: init `settings.colors` to null and explicitely check for `settings.colors === false`, thus fixing the bug AND avoiding making unnecessary api calls

fix: missing icon colors on first load

---

src/hooks/useNotifications.ts
src/utils/auth.ts
src/utils/helpers.test.ts
src/utils/helpers.ts

Consolidate `isEnterprise` logic

refactor: is enterprise host fn

---

src/typesGithub.ts
src/utils/__snapshots__/github-api.test.ts.snap
src/utils/github-api.test.ts
src/utils/github-api.ts

Also sort switch by alphabetic state type

test: add notification color coverage

---

src/components/Repository.test.tsx
src/components/Repository.tsx
src/components/__snapshots__/Repository.test.tsx.snap
src/context/App.tsx
src/hooks/useNotifications.test.ts
src/hooks/useNotifications.ts

Implements a "Mark repository as done" button, as discussed in #706
We had concerns about rate-limiting but [according to Github API's the limit is 5000 calls per hour](https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api?apiVersion=2022-11-28#primary-rate-limit-for-authenticated-users); so I don't think we need to worry about it.
I added a space between repository icons so they are aligned with `NotificationRow` icons, but it can be removed if https://github.com/gitify-app/gitify/pull/784 is implemented

feat: mark repository as done

---

src/typesGithub.ts
src/utils/__snapshots__/github-api.test.ts.snap
src/utils/github-api.test.ts
src/utils/github-api.ts

feat: add member_feature_requested reason

---

main.js

It looks like the bug has been resolved; I'm running MacOS and I've had no issues with `showDockIcon: false`.
I think we can simply drop this function (I added `showDockIcon: false` to make it more explicit, even though it was already the default value)

chore: remove `delayedHideAppIcon()`

---

src/typesGithub.ts
src/utils/__snapshots__/github-api.test.ts.snap
src/utils/github-api.test.ts
src/utils/github-api.ts

feat: add security_advisory_credit reason

---

src/utils/helpers.ts

Add missing type info (`string`) to function and variable

fix: add type to urls

---

src/utils/helpers.test.ts
src/utils/helpers.ts

feat: support repository invitation links

---

src/components/NotificationRow.tsx
src/typesGithub.ts
src/utils/__snapshots__/github-api.test.ts.snap
src/utils/github-api.test.ts
src/utils/github-api.ts

feat: support icons/colors for checksuite / workflow notifications

---

src/typesGithub.ts
src/utils/__snapshots__/github-api.test.ts.snap
src/utils/github-api.test.ts
src/utils/github-api.ts

As per https://docs.github.com/en/rest/activity/notifications?apiVersion=2022-11-28#about-notification-reasons

feat: add support for `approval_requested` reason

---

src/__mocks__/mockedData.ts
src/hooks/useNotifications.test.ts
src/hooks/useNotifications.ts
src/typesGithub.ts
src/utils/__snapshots__/github-api.test.ts.snap
src/utils/github-api.test.ts
src/utils/github-api.ts
src/utils/helpers.ts

Closes: #813
Uses the GraphQL API to fetch the Discussion `stateReason`

feat: support discussion state types

---

src/typesGithub.ts

Split Issue Types to match the schema documented at https://docs.github.com/en/rest/issues/issues?apiVersion=2022-11-28#get-an-issue
Add comment to PullRequestStateType as `merged` and `draft` are not officially part of https://docs.github.com/en/rest/pulls/pulls?apiVersion=2022-11-28#get-a-pull-request

refactor: split issue state types and document pullrequest state type

---

src/typesGithub.ts
src/utils/state.test.ts
src/utils/state.ts

Improve match accuracy by using regex to extract all CheckSuite title attributes

feat: use regex to extract all checksuite attributes

---

src/hooks/useNotifications.test.ts
src/typesGithub.ts
src/utils/state.test.ts
src/utils/state.ts

Use regex to match workflow run titles and extract attributes.  Will support https://github.com/gitify-app/gitify/issues/526

feat: use regex to extract workflow-run attributes

---

src/utils/__snapshots__/github-api.test.ts.snap
src/utils/appearance.ts
src/utils/github-api.ts

feat: simplify icon colors and improve accessibility when in light-mode

---

src/utils/helpers.test.ts
src/utils/helpers.ts

Closes https://github.com/gitify-app/gitify/issues/526

feat: link workflow run notifications to actions

---

src/__mocks__/mockedData.ts
src/typesGithub.ts
src/utils/helpers.ts
src/utils/state.test.ts
src/utils/state.ts

Closes #831
Since we aren't using any of the relay paginated information in the GraphQL search responses, we can simplify and use the `nodes` shorthand

refactor: use nodes shorthand in graphql queries

---

src/utils/helpers.test.ts
src/utils/helpers.ts

Closes https://github.com/gitify-app/gitify/issues/381

feat: link checksuite notifications to actions

---

src/components/NotificationRow.tsx
src/components/__snapshots__/NotificationRow.test.tsx.snap
src/utils/helpers.test.ts
src/utils/helpers.ts

This PR adds text which shows when mousing over the notification icons.
The text is formatted based on the notification subject type and reason (if applicable)
*Examples*

feat: add hover title text to icons

---

package.json
pnpm-lock.yaml

Addresses a CRITICAL vuln by overriding the version of @babel/traverse.
This change is the result of running `pnpm audit --fix && pnpm install`

build: override @babel/traverse version

---

src/components/Sidebar.test.tsx
src/components/Sidebar.tsx
src/components/__snapshots__/Sidebar.test.tsx.snap
src/routes/Login.tsx
src/routes/LoginEnterprise.tsx
src/routes/LoginWithToken.tsx
src/routes/Settings.test.tsx
src/routes/Settings.tsx
src/routes/__snapshots__/Login.test.tsx.snap
src/routes/__snapshots__/LoginEnterprise.test.tsx.snap
src/routes/__snapshots__/LoginWithToken.test.tsx.snap
src/routes/__snapshots__/Settings.test.tsx.snap

Ensure each button has a `label` property for hover-over text, and that `aria-label` for accessibility is set appropriately for icons

refactor: ensure all buttons have label and accessibility text

---

src/components/NotificationRow.tsx
src/components/__snapshots__/NotificationRow.test.tsx.snap

For situations when the title is truncated, this enhancement allows you to see the full notification title on hover

feat: add title to notification heading

---

src/__mocks__/mockedData.ts
src/components/NotificationRow.tsx
src/components/__snapshots__/NotificationRow.test.tsx.snap
src/hooks/useNotifications.test.ts
src/hooks/useNotifications.ts
src/typesGithub.ts
src/utils/helpers.ts
src/utils/subject.test.ts
src/utils/subject.ts

Closes #439
Shows the last update user when available.
Currently this logic is part of the subject enrichment process, which is controlled by `SettingsState.colors`.   Perhaps this setting should be renamed to something more suitable now that it handles fetching notification state/color and notification last updated user details

feat: show notification last update user

---

src/utils/subject.test.ts
src/utils/subject.ts

Refactor subject to not export each function and extract user logic

refactor: subject exports and tests

---

package.json
pnpm-lock.yaml

Resolves https://github.com/gitify-app/gitify/issues/696
After exhaustive testing, electron@20 or higher causes the issue
Once merged, I'll mark the new Renovate electron@20 PR as requiring code changes to prevent macos startup crashes

fix(deps): downgrade to electron@19 to resolve macos code signing and startup crash

---

.github/workflows/release.yml

Allow us to manually run the release workflow to confirm things like code-signing in future

build: allow release workflow to be run manually

---

src/typesGithub.ts
src/utils/subject.test.ts
src/utils/subject.ts

Add `Release` user notification details.
Refactored tests and extracted user lookup into a common function.

feat: add release user

---

src/utils/subject.test.ts
src/utils/subject.ts

Use issue/pr user as default case which increases the coverage of notification scenarios

feat: fallback to issue/pr user

---

src/components/Sidebar.tsx
src/components/__snapshots__/Sidebar.test.tsx.snap

fix: hide default orange outline around gitify logo on first start

---

src/routes/Settings.test.tsx
src/routes/Settings.tsx
src/routes/__snapshots__/Settings.test.tsx.snap

Hyperlink app version information in Settings page to the matching Gitify release notes

feat: link version number to release notes

---

src/routes/Settings.tsx
src/routes/__snapshots__/Settings.test.tsx.snap

Adjust top and bottom padding/margins in preparation for #929 
**Before**
**After**

refactor(settings): adjust margins

---

package.json
pnpm-lock.yaml

We no longer need this @babel/traverse override.  Once merged, I'll prepare a v5.1.0 release

chore(deps): remove babel/traverse override

---

src/__mocks__/mockedData.ts
src/hooks/useNotifications.ts
src/routes/__snapshots__/Notifications.test.tsx.snap
src/typesGithub.ts
src/utils/helpers.ts

Fixes #944 
Previously we were not using the correct enterprise token for generating notification title url links.
This change extends the Notification type to pass the hostname along with it (previously was only stored adjacent), creates a new helper for getting the correct auth token, and uses this to make subsequent authenticated api calls.

fix: ensure correct token is used

---

src/__mocks__/mock-state.ts
src/components/fields/Checkbox.tsx
src/components/fields/RadioGroup.tsx
src/components/fields/__snapshots__/RadioGroup.test.tsx.snap
src/context/App.test.tsx
src/context/App.tsx
src/routes/Settings.test.tsx
src/routes/Settings.tsx
src/routes/__snapshots__/Settings.test.tsx.snap
src/types.ts
src/utils/github-api.ts
src/utils/storage.test.ts
src/utils/theme.test.ts
src/utils/theme.ts

Redesign the *Settings* screen so that it supports our growing configuration options (ie: #945).
Main changes include
* fixed header
* fixed footer
* scrollable settings section
* group settings into three distinct buckets (appearance, notification, system)
* rename `settings.appearance` -> `settings.theme`

feat: redesign settings ux

---

src/routes/Settings.test.tsx
src/routes/Settings.tsx
src/routes/__snapshots__/Settings.test.tsx.snap

Clarify that `showNotifications` is for native system notifications.  Move to new **System** section

refactor: clarify show notifications setting

---

src/routes/Login.tsx
src/routes/LoginWithToken.tsx
src/routes/__snapshots__/Login.test.tsx.snap
src/routes/__snapshots__/LoginWithToken.test.tsx.snap

Until we have the opportunity to resolve the OAuth Login flow, let's disable it and promote PAT as a interim method

refactor: temporarily disable oauth login method

---

src/components/Sidebar.tsx
src/components/__snapshots__/Sidebar.test.tsx.snap

Adds a small animation as loading state to the "Refresh Notifications" button, shown when notifications are fetching.

fix: Add loading state to "Refresh Notifications" button

---

package.json

Currently, a bunch of unnecessary permissions end up in the macOS `Info.plist` file, in particular these
```
<key>NSBluetoothAlwaysUsageDescription</key>
<string>This app needs access to Bluetooth</string>
<key>NSBluetoothPeripheralUsageDescription</key>
<string>This app needs access to Bluetooth</string>
<key>NSCameraUsageDescription</key>
<string>This app needs access to the camera</string>
<key>NSMainNibFile</key>
<string>MainMenu</string>
<key>NSMicrophoneUsageDescription</key>
<string>This app needs access to the microphone</string>
```
After some googling, there is a (not very well documented) way to override these.
Below is the before and after of this change.  From my local testing, `Play Sound` events still happen
<details>
<summary>Before</summary>
```
<?xml version="1.0" …
```

build: override unnecessary permissions

---

src/components/NotificationRow.tsx
src/components/__snapshots__/NotificationRow.test.tsx.snap

Back by popular demand (and muscle memory)

feat: bring back ability to click full notification row

---

src/utils/helpers.ts

Ensure there is always a url to open

refactor: default to repo url

---

src/__mocks__/mock-state.ts
src/context/App.test.tsx
src/context/App.tsx
src/routes/Notifications.test.tsx
src/routes/Notifications.tsx
src/routes/Settings.test.tsx
src/routes/Settings.tsx
src/routes/__snapshots__/Notifications.test.tsx.snap
src/routes/__snapshots__/Settings.test.tsx.snap
src/types.ts

Allow user to specify if they want to show notification hostname.  Currently, this will only show if multiple accounts are authenticated.

feat(settings): show account hostname

---

src/routes/Settings.test.tsx
src/routes/Settings.tsx
src/routes/__snapshots__/Settings.test.tsx.snap

feat(settings): display username on logout hover

---

.gitattributes

Snapshots make it a bit more annoying to review PRs. This improves that using a Github feature. See the comment for more info.
Files marked as linguist-generated:
* Are collapsed by default in pull request diffs, making code reviews more focused and manageable.
* Do not contribute to the repository's language statistics, keeping the language breakdown more relevant to the human-generated codebase.

chore: auto-collapse snaphsots in PRs

---

.husky/pre-commit

Since enabling `collectCoverage` by default, husky will routinely fail since the changes files do not cover the test cases to get a correct coverage gating measure.
Changing to run all tests as part of the husky pre-commit hook. I think this OK.
Alternatively, if we want to continue running on changes files only, we could disable the coverage check
`pnpm test -- --onlyChanged --collectCoverage=false`

build: husky run all tests

---

src/components/fields/FieldInput.tsx
src/routes/LoginWithToken.test.tsx
src/routes/LoginWithToken.tsx
src/routes/__snapshots__/LoginEnterprise.test.tsx.snap
src/routes/__snapshots__/LoginWithToken.test.tsx.snap

Main updates
- improve formatting of content
- simplify help text descriptions
- simplify Generate PAT
- new PAT url includes date created (inspired by Graphite experience).
| Current | New |
| --- | --- |
|![Screenshot 2024-04-11 at 10 15 04 AM](https://github.com/gitify-app/gitify/assets/386277/345fe71f-d37d-4afa-885a-9ddc00d7e8fc)![Screenshot 2024-04-11 at 10 16 10 AM](https://github.com/gitify-app/gitify/assets/386277/37a5c09f-498c-43b7-892d-0b7cb8842a5e) |![Screenshot 2024-04-11 at 10 02 57 AM](https://github.com/gitify-app/gitify/assets/386277/b8534c67-8923-45ea-b949-ed3b17273a9a)  ![Screenshot 2024-04-11 at 10 07 40 AM](https://github.com/gitify-app/gitify/assets/386277/8c040f6f-db33-45d4-86f0-ce2baf04f386) |

refactor: improve PAT login experience

---

src/components/fields/Checkbox.test.tsx
src/components/fields/Checkbox.tsx
src/components/fields/FieldInput.test.tsx
src/components/fields/FieldInput.tsx
src/components/fields/RadioGroup.test.tsx
src/components/fields/RadioGroup.tsx
src/components/fields/__snapshots__/Checkbox.test.tsx.snap
src/components/fields/__snapshots__/RadioGroup.test.tsx.snap
src/routes/Settings.tsx
src/routes/__snapshots__/Settings.test.tsx.snap

This PR includes a number of cleanup and consistency items, including
- consistent naming of components and prop interfaces
- rename optional placeholder -> helpText for checkbox and radio groups
- fix formatting of helpText for checkbox and radio groups
- add optional disabled prop to radio groups
- 100% test coverage (statements, branches, functions, lines, oh my!)

refactor: field components

---

src/hooks/useNotifications.ts
src/routes/Settings.test.tsx
src/routes/Settings.tsx
src/routes/__snapshots__/Settings.test.tsx.snap

Also make it null safe for notifications that don't have users (ie: workflow runs)

fix(settings): allow showBots only when detailedNotifications is selected

---

src/components/fields/Checkbox.tsx
src/components/fields/Tooltip.test.tsx
src/components/fields/Tooltip.tsx
src/components/fields/__snapshots__/Tooltip.test.tsx.snap
src/routes/Settings.test.tsx
src/routes/Settings.tsx
src/routes/__snapshots__/Settings.test.tsx.snap

feat: add tooltip for show participating setting

---

src/routes/Settings.test.tsx
src/routes/__snapshots__/Settings.test.tsx.snap

Organize settings tests into test suites based upon the settings sections (general, appearance, notifications, system, footer)

test(settings): organize by section

---

src/hooks/useNotifications.ts

Moves the setRequestFailed(false) into the earliest location we have a successful response.
Fixes UI "flickering" when the app gets in an error state, such as rate-limiting (clicking refresh would flicker between notifications and the error page)

fix: relocate set request status succeeded 

---

src/routes/Settings.tsx

I've been seeing the following warning/error in the console when running locally
```
(node:7668) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 update-native-theme listeners added to [IpcRenderer]. Use emitter.setMaxListeners() to increase limit
```
Moving this into the useEffect along with the other ipcRenderer calls seems to alleviate this.  Tested by toggling theme within the Gitify app, as well as via the macOS system settings and all seemed to behave as anticipated.

fix: move `update-native-theme` into ipcRenderer `useEffect`

---

main.js

#1034 
Small tweak to retrieve the previous `zoomFactor` on app start

fix: preserve `zoomFactor` on restarts

---

src/routes/Settings.tsx

Looks like the Electron method we're using for the `showNotificationsCountInTray` setting [is MacOS only](https://www.electronjs.org/docs/latest/api/tray#traysettitletitle-options-macos) 🙈

fix: only show `showNotificationsCountInTray` setting on MacOS

---

src/components/NotificationRow.tsx

After exhaustive debugging and testing locally, it would appear that this single change has solved the funky notification state issues.
This could be reliably recreated by performing the following steps, quickly, before the interval fetchNotifications runs
* marking a notification as read (remove from state)
* clicking on another notification title
Also took the opportunity to clarify the name of the function

fix: inconsistent notification state

---

src/components/Sidebar.test.tsx
src/components/Sidebar.tsx
src/context/App.test.tsx
src/context/App.tsx

fix: duplicate system notifications

---

src/hooks/useNotifications.test.ts
src/hooks/useNotifications.ts
src/utils/api/errors.test.ts
src/utils/api/errors.ts

Piece by piece carving useNotifications back to something bite-sized

refactor(api/errors): move error function and tests out

---

.github/workflows/on-tag.yml

Closes #1028 
Successfully tested here
* workflow: https://github.com/gitify-app/gitify/actions/runs/8754907654/job/24027797143
* pr: https://github.com/gitify-app/website/pull/108
Note: PR author/ownership cannot be changed as per https://github.com/peter-evans/create-pull-request/issues/2779

fix: website version bump workflow

---

src/hooks/useNotifications.test.ts

Looks like I missed this when renaming `settings.colors` to `settings.detailedNotifications` 🙈

test: rename suite

---

src/components/Loading.test.tsx
src/components/Loading.tsx
src/components/Sidebar.tsx
src/context/App.tsx
src/hooks/useNotifications.test.ts
src/hooks/useNotifications.ts
src/routes/Notifications.test.tsx
src/routes/Notifications.tsx
src/types.ts

Thanks @mattpocock for [todays inspiration](https://www.linkedin.com/feed/update/urn:li:activity:7188480362300211200?updateEntityUrn=urn%3Ali%3Afs_feedUpdate%3A%28V2%2Curn%3Ali%3Aactivity%3A7188480362300211200%29)

refactor: use status type (loading, error, success)

---

src/__mocks__/mockedData.ts
src/hooks/useNotifications.test.ts
src/hooks/useNotifications.ts
src/routes/__snapshots__/Notifications.test.tsx.snap
src/typesGitHub.ts

🧼 consolidate response handling for both github cloud and github server accounts.

refactor: simplify useNotifications

---

src/hooks/useNotifications.ts
src/utils/helpers.ts

Update further instances to use `getTokenForHost` helper

refactor: get token for host

---

src/utils/subject.test.ts
src/utils/subject.ts

Move the try/catch to the main entry, `getGitifySubjectDetails` and add test coverage

refactor: broaden try/catch and add coverage

---

src/__mocks__/mockedData.ts
src/utils/api/client.ts
src/utils/helpers.ts

Instead of comparing createdAt timestamps, we can use the GraphQL query variables to fetch the latest comment and latest reply

refactor(discussions): use API to get latest comment and reply

---

src/utils/api/client.test.ts
src/utils/api/client.ts
src/utils/api/utils.test.ts
src/utils/api/utils.ts
src/utils/helpers.test.ts
src/utils/helpers.ts

Further refactoring to favor using URL objects rather than string manipulation

refactor: use URL object instead of strings

---

src/__mocks__/mock-state.ts
src/components/NotificationRow.tsx
src/components/__snapshots__/NotificationRow.test.tsx.snap
src/context/App.test.tsx
src/context/App.tsx
src/hooks/useNotifications.test.ts
src/hooks/useNotifications.ts
src/routes/Settings.test.tsx
src/routes/Settings.tsx
src/routes/__snapshots__/Settings.test.tsx.snap
src/types.ts
src/utils/constants.ts
src/utils/remove-notification.test.ts
src/utils/remove-notification.ts

Add new **Notification Settings** which allows users to "delay" notifications from being removed from Gitify upon user interactions (marked as done, marked as read, open).
When enabled, notification rows will be set temporarily as opaque until they're removal upon next refresh (scheduled or user initiated).
Defaulted to disabled.
**Demo**
https://github.com/gitify-app/gitify/assets/386277/812a2f1c-0a15-406d-91c1-00210b432387
Closes #319

feat: delay notification removal

---

src/utils/api/client.ts
src/utils/api/utils.test.ts
src/utils/api/utils.ts

We were previously hardcoded to only use GitHub Cloud's GraphQL API.
This enhancement now supports GitHub Server users

feat: support discussions for github server

---

src/routes/LoginEnterprise.test.tsx
src/routes/LoginEnterprise.tsx
src/routes/__snapshots__/LoginEnterprise.test.tsx.snap
src/utils/auth.test.ts
src/utils/auth.ts

Add help text to create a new OAuth Application.

feat(auth): add `create oauth app` link to enterprise route

---

src/routes/LoginEnterprise.test.tsx
src/routes/LoginEnterprise.tsx
src/routes/LoginWithToken.test.tsx
src/routes/LoginWithToken.tsx
src/routes/__snapshots__/LoginEnterprise.test.tsx.snap
src/routes/__snapshots__/LoginWithToken.test.tsx.snap

Add help docs to the bottom left of each login flow.

feat(login): add help docs to login flows

---

src/routes/Settings.test.tsx
src/routes/Settings.tsx
src/routes/__snapshots__/Settings.test.tsx.snap
src/typesGitHub.ts
src/utils/api/__snapshots__/client.test.ts.snap
src/utils/api/client.test.ts
src/utils/api/client.ts

refactor(auth): remove repo scopes check

---

src/app.tsx
src/components/fields/Button.tsx
src/components/fields/__snapshots__/Button.test.tsx.snap
src/routes/Login.test.tsx
src/routes/Login.tsx
src/routes/LoginWithOAuthApp.test.tsx
src/routes/LoginWithOAuthApp.tsx
src/routes/LoginWithPersonalAccessToken.test.tsx
src/routes/LoginWithPersonalAccessToken.tsx
src/routes/Settings.test.tsx
src/routes/Settings.tsx
src/routes/__snapshots__/Login.test.tsx.snap
src/routes/__snapshots__/LoginWithOAuthApp.test.tsx.snap
src/routes/__snapshots__/LoginWithPersonalAccessToken.test.tsx.snap
src/routes/__snapshots__/Settings.test.tsx.snap

Adopt GitHub's terminology and icons for  `Personal Access Token` or `OAuth App` authentication methods. 
One further step closer to cleaning up our auth modules...

refactor(auth): update ux and terminology

---

.github/workflows/release.yml

According to https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes#example-configurations - this _should_ help with our release notes process

build: changelog automation

---

src/__mocks__/state-mocks.ts
src/components/NotificationRow.test.tsx
src/components/NotificationRow.tsx
src/context/App.test.tsx
src/context/App.tsx
src/hooks/useNotifications.test.ts
src/routes/LoginWithOAuthApp.test.tsx
src/routes/LoginWithOAuthApp.tsx
src/routes/Settings.test.tsx
src/routes/Settings.tsx
src/types.ts
src/utils/helpers.test.ts
src/utils/notifications.test.ts
src/utils/storage.test.ts
src/utils/storage.ts
src/utils/subject.test.ts

refactor(state): update state storage

---

src/context/App.test.tsx
src/context/App.tsx
src/hooks/useNotifications.test.ts
src/hooks/useNotifications.ts
src/routes/LoginWithOAuthApp.test.tsx
src/utils/auth.test.ts
src/utils/auth.ts
src/utils/helpers.ts
src/utils/notifications.ts

Further split from https://github.com/gitify-app/gitify/pull/1139

refactor: replace accounts with auth for AuthState

---

src/components/NotificationRow.tsx
src/context/App.tsx
src/routes/Settings.tsx

refactor: continued renaming of accounts to auth

---

src/__mocks__/state-mocks.ts
src/context/App.test.tsx
src/context/App.tsx
src/routes/LoginWithOAuthApp.tsx
src/routes/LoginWithPersonalAccessToken.test.tsx
src/routes/LoginWithPersonalAccessToken.tsx
src/types.ts
src/utils/auth/auth.test.ts
src/utils/auth/types.ts
src/utils/auth/utils.test.ts
src/utils/auth/utils.ts

Further split from #1139 
* rename login methods 
* move common logic into a `utils/auth` folder

refactor: login methods and options

---

src/utils/helpers.test.ts
src/utils/helpers.ts

I'm take a bit of an educated guess, but this should catch any null or split issues with our use of date-fns lib
Fixes: #1166

fix: add datetime error handling

---

src/components/NotificationRow.tsx
src/components/__snapshots__/NotificationRow.test.tsx.snap
src/utils/constants.ts

Use "pill" to group icon and metric.  Matches that of the GitHub Mobile UX

feat: format notification metrics within "pills"

---

src/utils/auth/migration.test.ts

Cleaning up another test output:

fix: cleanup migration test output

---

src/components/NotificationRow.test.tsx
src/components/NotificationRow.tsx
src/components/__snapshots__/NotificationRow.test.tsx.snap
src/typesGitHub.ts
src/utils/subject.ts

feat: milestone indicator

---

src/components/NotificationRow.tsx
src/components/__snapshots__/NotificationRow.test.tsx.snap
src/utils/constants.ts

handful of small tailwind tweaks
- prevent avatar from being shrunk on overflow
- allow horizontal scrolling on overflow (for notifications with lots of pills. This is a little quirky, so open to suggestions on a better method)
- simplify margins by using gap

refactor: update notification footer styles

---

src/components/fields/Tooltip.tsx
src/components/fields/__snapshots__/Tooltip.test.tsx.snap

fix: tooltip z index to prevent items showing through

---

src/__mocks__/state-mocks.ts
src/components/NotificationRow.test.tsx
src/components/NotificationRow.tsx
src/components/__snapshots__/NotificationRow.test.tsx.snap
src/context/App.test.tsx
src/context/App.tsx
src/routes/Settings.test.tsx
src/routes/Settings.tsx
src/routes/__snapshots__/Settings.test.tsx.snap
src/types.ts

Add display setting to toggle showing metric pills

feat: add pill display settings

---

src/components/NotificationRow.tsx
src/components/Repository.tsx
src/components/__snapshots__/NotificationRow.test.tsx.snap
src/components/__snapshots__/Repository.test.tsx.snap
src/utils/constants.ts
src/utils/helpers.ts
tailwind.config.js

Some further changes are sleeping on https://github.com/gitify-app/gitify/pull/1177
Changes
* update tailwind css classes
* shrink pills to xss (via custom tailwind font size)
* allow pills to flex wrap to new line if too long
* change updated [datetime to use strict formatting](https://date-fns.org/v3.6.0/docs/formatDistanceToNowStrict) (removes the `about` prefix and is more precise) - saves some horizontal space.
* truncate long repo names or notification titles
Exaggerated example (i locally duplicated the linked issues pills to demonstrate)

refactor: more pill css changes

---

src/__mocks__/state-mocks.ts
src/context/App.test.tsx
src/context/App.tsx
src/hooks/useNotifications.test.ts
src/hooks/useNotifications.ts
src/utils/notifications.test.ts
src/utils/notifications.ts

Pass GitifyState instead of AuthState and SettingsState separately

refactor: use gitify state

---

README.md
package.json

This PR fixes the FAQ link in the README.md file and updates the package.json `lint-staged` script to remove `.md` files.
Biome does not support markdown in its language support list (see here: https://biomejs.dev/internals/language-support/) hence the `lint-stage` script was failing for any change in the `README.md` file.
- Fix FAQ link in README.md
- Remove `.md` from `lint-staged` script

fix: FAQ link in README.md

---

src/routes/Settings.tsx

Fix an edge-case bug.
If you changed the theme within the app, and also changed your native system theme, the updates were not consistently being reflected unless you restarted.

fix: theme state

---

main.js
src/__mocks__/electron.js
src/components/Sidebar.test.tsx
src/components/Sidebar.tsx
src/routes/Accounts.test.tsx
src/routes/Login.test.tsx
src/routes/Login.tsx
src/routes/Settings.test.tsx
src/routes/Settings.tsx
src/utils/comms.test.ts
src/utils/comms.ts
src/utils/notifications.test.ts
src/utils/notifications.ts

Rename all custom ipc events to be prefixed with `gitify`.
Consolidate ipcRenderer.send / ipcRenderer.invoke within comms.ts
Update tests to mock comms instead of mocking ipcRenderer

refactor: prefix all gitify custom ipc events. consolidate under comms

---

src/components/NotificationRow.tsx
src/components/Sidebar.tsx
src/routes/Accounts.tsx
src/routes/Settings.tsx
src/routes/__snapshots__/Settings.test.tsx.snap
src/styles/gitify.ts
src/utils/constants.ts
src/utils/remove-notification.test.ts
src/utils/remove-notification.ts

Move style constants into dedicated class.

refactor: move custom styles into class

---

.github/workflows/release.yml

~use default auto provisioned GitHub actions token instead of my custom PAT~
remove gh_token env variable. should use `github_token`

build(release): remove gh_token env

---

src/components/NotificationRow.test.tsx
src/components/Repository.test.tsx
src/components/Sidebar.test.tsx
src/routes/Accounts.test.tsx
src/routes/Settings.test.tsx

Mock openExternalLink comms fn instead of electron shell

refactor: mock openExternalLink comms fn

---

main.js

No longer part of https://www.electronjs.org/docs/latest/api/structures/web-preferences
Googling around, seems like it was removed some time ago...

refactor: remove deprecated overlay scrollbar option

---

src/utils/subject.test.ts
src/utils/subject.ts

Bot generated PRs (eg: RenovateBot) contain release notes which typically have lots of linked issues.
this PR limits linked issue extraction to those generated by a User

feat: only extract linked issues for User PRs

---

src/components/NotificationRow.tsx
src/components/__snapshots__/NotificationRow.test.tsx.snap
src/components/buttons/PillButton.test.tsx
src/components/buttons/PillButton.tsx
src/components/buttons/__snapshots__/PillButton.test.tsx.snap
src/styles/gitify.ts

thanks for the nudge @bmulholland

refactor: new pill component

---

package.json
pnpm-lock.yaml
src/components/NotificationRow.tsx
src/components/Repository.tsx
src/components/Sidebar.tsx
src/components/__snapshots__/NotificationRow.test.tsx.snap
src/components/__snapshots__/Repository.test.tsx.snap
src/components/buttons/PillButton.tsx
src/components/fields/Button.tsx
src/components/fields/__snapshots__/Button.test.tsx.snap
src/routes/Login.tsx
src/routes/LoginWithOAuthApp.tsx
src/routes/LoginWithPersonalAccessToken.tsx
src/routes/__snapshots__/LoginWithOAuthApp.test.tsx.snap
src/routes/__snapshots__/LoginWithPersonalAccessToken.test.tsx.snap
src/utils/cn.test.ts
src/utils/cn.ts
tsconfig.json

refactor: deprecate react-transition-group over tailwind animations

---

src/utils/helpers.test.ts
src/utils/helpers.ts

revert the enhancement from https://github.com/gitify-app/gitify/pull/1103 as it was causing some odd behavior for long-running issues/prs getting out of sync and showing the last read date rather than the new updated date

fix: revert updated_at formatting

---

biome.json
src/__mocks__/electron.js
src/components/AccountNotifications.tsx
src/components/NotificationRow.tsx
src/components/Repository.tsx
src/context/App.tsx
src/hooks/useNotifications.ts
src/routes/Accounts.tsx
src/routes/LoginWithOAuthApp.tsx
src/routes/LoginWithPersonalAccessToken.tsx
src/utils/auth/utils.test.ts
src/utils/auth/utils.ts
src/utils/theme.test.ts

A selection of updates to remove biome warnings, including:
- ensure all callbacks specify their dependencies
- enable `noUnusedFunctionParamaters` nursery rule and fix lint errors
- enable `useDefaultSwitchClause` nursery rule and fix lint errors

refactor: biome linter updates

---

src/routes/Settings.test.tsx
src/routes/Settings.tsx
src/routes/__snapshots__/Settings.test.tsx.snap
src/utils/links.test.ts
src/utils/links.ts

A small enhancement to help when doing local development remember which version of the app is running 😎

feat: set app version as `dev` when building locally

---

index.html
src/components/AllRead.tsx
src/components/Oops.tsx
src/components/__snapshots__/AllRead.test.tsx.snap
src/components/__snapshots__/Oops.test.tsx.snap
src/components/fields/FieldInput.tsx
src/components/fields/__snapshots__/FieldInput.test.tsx.snap
src/routes/Accounts.tsx
src/routes/Login.tsx
src/routes/LoginWithOAuthApp.tsx
src/routes/LoginWithPersonalAccessToken.tsx
src/routes/Notifications.tsx
src/routes/Settings.tsx
src/routes/__snapshots__/Accounts.test.tsx.snap
src/routes/__snapshots__/Login.test.tsx.snap
src/routes/__snapshots__/LoginWithOAuthApp.test.tsx.snap
src/routes/__snapshots__/LoginWithPersonalAccessToken.test.tsx.snap
src/routes/__snapshots__/Notifications.test.tsx.snap
src/routes/__snapshots__/Settings.test.tsx.snap

Cleanup a bunch of useless `flex-1`s and centralize the global `bg` and `text` colors into `index.html`.
Also fixed a bug in the login pages where the label was not being correctly set.

style: cleanup useless tw classnames

---

src/components/AllRead.tsx
src/components/__snapshots__/AllRead.test.tsx.snap

fix regression from #1238 for AllRead UI not being vertically centered

fix: regression in all read ui

---

.github/workflows/build.yml
.github/workflows/release.yml
.github/workflows/test.yml

Update to use `macos-latest` tag now that it's equal to `macos-14` now
Also update our tests workflow to run on macos instead of ubuntu, since the maintainer group are all macos users.

build: use macos-latest runners

---

src/components/AccountNotifications.tsx
src/components/Repository.tsx
src/components/__snapshots__/AccountNotifications.test.tsx.snap
src/components/__snapshots__/Repository.test.tsx.snap

Idea here is to try to make the notification the primary thing the user looks at. We can potentially experiment an use lower opacities instead of this 10 point jump.

style: opacity hierarchy

---

src/components/AccountNotifications.tsx
src/components/Repository.test.tsx
src/components/Repository.tsx
src/components/__snapshots__/AccountNotifications.test.tsx.snap
src/components/__snapshots__/Repository.test.tsx.snap

feat: toggle repository notification

---

src/components/NotificationRow.tsx
src/components/__snapshots__/NotificationRow.test.tsx.snap

Notification type icon was a bit too big from the information architecture perspective, so I reduced it to the size of the rest of the icons.
Before
After
Note: After includes fixes from other PRs.

style: notification type icon size

---

src/components/NotificationRow.test.tsx
src/components/NotificationRow.tsx
src/context/App.tsx
src/hooks/useNotifications.test.ts
src/styles/gitify.ts
src/utils/remove-notification.test.ts
src/utils/remove-notification.ts

fix regression issue from #1232 when using `delayNotificationState` setting. 
**_Before_** 
https://github.com/gitify-app/gitify/assets/386277/f90effda-9da2-485f-bf50-f617ff46a739
**_After_** 
https://github.com/gitify-app/gitify/assets/386277/02096ffa-9bfa-4924-a027-5ee73993f77c

fix: regression in delay notification state behavior

---

biome.json
src/components/AccountNotifications.tsx
src/components/NotificationRow.test.tsx
src/components/NotificationRow.tsx
src/components/Repository.test.tsx
src/components/Repository.tsx
src/components/__snapshots__/AccountNotifications.test.tsx.snap
src/components/__snapshots__/NotificationRow.test.tsx.snap
src/components/__snapshots__/Repository.test.tsx.snap

Adds the functionality that was referred to in https://github.com/gitify-app/gitify/pull/1245#issuecomment-2171428582
Also sorted the order of the buttons to try to attain some added consistency.

style: toggle on row click & action buttons order

---

src/__mocks__/state-mocks.ts
src/components/AccountNotifications.test.tsx
src/components/AccountNotifications.tsx
src/components/NotificationRow.test.tsx
src/components/NotificationRow.tsx
src/components/RepositoryNotifications.tsx
src/components/__snapshots__/AccountNotifications.test.tsx.snap
src/components/__snapshots__/NotificationRow.test.tsx.snap
src/context/App.test.tsx
src/context/App.tsx
src/routes/Settings.test.tsx
src/routes/Settings.tsx
src/routes/__snapshots__/Settings.test.tsx.snap
src/types.ts

closes #836.  
for now I've added this as another `Notification Setting` flag. 
---
I've been thinking that in the near future it may make sense to pull out all of our filter-based settings into either their:
- own settings section ie: `Notification Filters`
- dedicated `Filters` page with access from the sidebar  
Types of filter-based settings would include 
- group by repository or date
- show/hide Bot notifications
- show/hide by notification reason #264 
- etc

feat: group notifications by repository or date

---

CONTRIBUTING.md
README.md

This also vastly clears up our readme making it much more appealing to non-contributors (most users).
Closes #655.

docs: create contributing and add project philosophy

---

src/components/NotificationRow.tsx

favor groupByDate instead of !groupByRepository now that we're not storing it as a boolean

refactor: invert groupBy to avoid negative conditions

---

src/components/AccountNotifications.tsx
src/components/NotificationRow.tsx
src/components/RepositoryNotifications.tsx
src/components/__snapshots__/AccountNotifications.test.tsx.snap
src/components/__snapshots__/NotificationRow.test.tsx.snap
src/components/__snapshots__/RepositoryNotifications.test.tsx.snap

refactor: subtle ui tweaks

---

src/components/__snapshots__/AllRead.test.tsx.snap
src/utils/constants.ts

A handful of emoji library updates for 
- all read
- missing scopes
- default error (oops)
Any others you'd like to see?

refactor: emoji updates

---

CONTRIBUTING.md
package.json
src/electron/main.js

I'd argue the "old" settings were not really useful, so I've also removed them.

chore: automatically open devtools on local development

---

src/components/settings/AppearanceSettings.test.tsx
src/components/settings/AppearanceSettings.tsx
src/components/settings/Legend.test.tsx
src/components/settings/Legend.tsx
src/components/settings/NotificationSettings.test.tsx
src/components/settings/NotificationSettings.tsx
src/components/settings/SettingsFooter.test.tsx
src/components/settings/SystemSettings.test.tsx
src/components/settings/SystemSettings.tsx
src/components/settings/__snapshots__/Legend.test.tsx.snap
src/components/settings/__snapshots__/SettingsFooter.test.tsx.snap
src/routes/__snapshots__/Settings.test.tsx.snap

I was going crazy with the misalignment 🤪

style: legend text and icon alignment

---

.husky/pre-commit
jest.config.ts
package.json

Running all tests (before each commit) just takes way too long 😢 
However, this interferes with the coverage threshold, which should be fine since we still have coveralls on a per PR basis.

ci: run staged files' tests only

---

src/utils/notifications.ts

fix: sound import

---

.github/workflows/label.yml

Add a simple workflow to check that at least one `label` is associated with each PR, as we use these to auto-generate release notes

build: check for PR labels

---

.husky/pre-commit

restore husky pre-commit that was accidentally removed in https://github.com/gitify-app/gitify/pull/1349

build(husky): restore pre-commit

---

src/electron/main.js

[context](https://github.com/gitify-app/gitify/pull/1397#issuecomment-2241898905)
The PR
1. introduces a `Developer` sub menu which contains
* `Toggle Developer Tools`
* `Reload`
2. Updates the `Toggle Developer Tools` accelerator keys to match the default Chrome hotkeys
3. Rename `Quit` to `Quit Gitify`
This will set us up for some new features as mentioned in https://github.com/gitify-app/gitify/issues/980

feat: developer context menu

---

src/utils/api/utils.ts
src/utils/helpers.test.ts
src/utils/helpers.ts

Clarify helper is for checking if a hostname is for GitHub Enterprise Server, rather than GitHub Cloud (free, enterprise, etc)

refactor: rename isEnterpriseHost helper

---

src/context/App.test.tsx
src/context/App.tsx
src/electron/main.js

Partially closes https://github.com/gitify-app/gitify/issues/980
Builds upon the former `logout` logic, now unused.

feat(developer): reset application

---

src/components/Sidebar.test.tsx
src/components/Sidebar.tsx
src/context/App.tsx
src/utils/auth/migration.ts
src/utils/links.test.ts
src/utils/links.ts

closes https://github.com/gitify-app/gitify/issues/1410

feat: use first account for quick link hostname

---

src/__mocks__/notifications-mocks.ts
src/components/AccountNotifications.test.tsx
src/components/AccountNotifications.tsx
src/components/AllRead.tsx
src/components/Oops.tsx
src/components/__snapshots__/AccountNotifications.test.tsx.snap
src/components/__snapshots__/AllRead.test.tsx.snap
src/components/__snapshots__/Oops.test.tsx.snap
src/context/App.tsx
src/hooks/useNotifications.test.ts
src/hooks/useNotifications.ts
src/routes/Notifications.test.tsx
src/routes/Notifications.tsx
src/routes/__snapshots__/Notifications.test.tsx.snap
src/types.ts
src/utils/notifications.ts

Closes https://github.com/gitify-app/gitify/issues/423
simulated multiple account setup with a partial failure

feat: gracefully handle partial failure for multiple accounts

---

src/hooks/useNotifications.ts
src/routes/Notifications.tsx
src/routes/__snapshots__/Notifications.test.tsx.snap

fix: clear global error state on fetch

---

src/context/App.tsx
src/utils/storage.ts

There was a bug that the "Create new OAuth App" button did not respond when pressing it to login again after deleting data.
This happens because loadState() is executed when opening the link, but once the data is deleted, localStorage becomes empty and loadState() returns null.
So I fixed this bug by saving the defalut states (defaultAuth and defaultSettings) when localStorage is empty.
After starting the app with `pnpm start` and then pressing the "Create new OAuth App" button, the error displayed was as follows
```
[44950:0809/151522.895514:INFO:CONSOLE(2)] "Uncaught TypeError: Cannot read properties of undefined (reading 'openLinks')", source: file:///Users/shiron/projects/gitify/build/js/app.js (2)
```

fix: openLinks on first login screen

---

src/routes/Accounts.tsx
src/routes/__snapshots__/Accounts.test.tsx.snap

Simple implementation to set the "primary account" (ie: first account), which is used for defining the hostname to use in the sidebar quick links

feat(accounts): set primary account

---

src/hooks/useNotifications.test.ts
src/hooks/useNotifications.ts
src/routes/Login.tsx
src/routes/LoginWithOAuthApp.tsx
src/routes/LoginWithPersonalAccessToken.tsx
src/utils/api/client.test.ts
src/utils/api/client.ts
src/utils/notifications.ts

Update all try/catch blocks to log errors

feat: improve error logging

---

src/components/Sidebar.tsx
src/components/__snapshots__/Sidebar.test.tsx.snap
src/context/App.tsx
src/hooks/useNotifications.ts

Upon logging out, notification counts metrics were still being shown in the Sidebar.
This PR ensures the upon logout the account is removed from account notifications state

fix: remove account notifications on logout

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/workflows/build.yml
CONTRIBUTING.md
package.json

https://github.com/gitify-app/gitify/releases/tag/v5.13.0

build: prepare `v5.13.0` release

---

src/routes/Accounts.test.tsx
src/routes/Accounts.tsx
src/routes/__snapshots__/Accounts.test.tsx.snap

Add `Login with GitHub App` option to account management screen.
Also simplify display of platform type to prevent overflow

feat: login with github app

---

src/__mocks__/partial-mocks.ts
src/__mocks__/state-mocks.ts
src/components/Sidebar.tsx
src/components/settings/SystemSettings.tsx
src/context/App.test.tsx
src/context/App.tsx
src/hooks/useNotifications.test.ts
src/routes/LoginWithOAuthApp.tsx
src/routes/Notifications.test.tsx
src/routes/Notifications.tsx
src/utils/api/errors.test.ts
src/utils/api/errors.ts
src/utils/api/utils.ts
src/utils/auth/migration.test.ts
src/utils/auth/migration.ts
src/utils/comms.ts
src/utils/constants.ts
src/utils/errors.ts
src/utils/links.test.ts
src/utils/links.ts
src/utils/storage.test.ts

goal is to slowly working towards separating the gitify specific constants/types from the github (or other platform) constants/types

refactor: extract error constants

---

src/utils/subject.test.ts
src/utils/subject.ts

feat: improve robustness of subject user handling

---

src/context/App.tsx

Upon first start, filters were not loaded before the first notification fetch occurred resulting in an inconsistent state.
This fixes it by simply restoring settings (and filters) before restoring accounts

fix: restore settings order

---

src/components/AccountNotifications.tsx
src/components/RepositoryNotifications.tsx
src/components/__snapshots__/AccountNotifications.test.tsx.snap
src/components/__snapshots__/RepositoryNotifications.test.tsx.snap

Use a chevron right icon when the headers are collapsed.  More intuitive UX.

refactor: change chevron type for closed sections

---

src/components/Sidebar.test.tsx
src/components/Sidebar.tsx
src/components/__snapshots__/Sidebar.test.tsx.snap
src/utils/links.test.ts
src/utils/links.ts

Change behavior for gitify icon to navigate home, instead of opening the gitify repository.  
Currently we can launch this by clicking on the application name + version in the Settings page.

feat: change icon navigation to go `home`

---

src/components/Sidebar.test.tsx
src/components/Sidebar.tsx
src/components/__snapshots__/Sidebar.test.tsx.snap

Change casing used for sidebar labels

refactor: update sidebar labels

---

src/utils/notifications.ts

Remove `Gitify` from the native notification title.  Frees up real-estate

refactor: native notification title

---

src/components/NotificationRow.test.tsx
src/components/NotificationRow.tsx
src/components/RepositoryNotifications.test.tsx
src/components/RepositoryNotifications.tsx
src/components/__snapshots__/AccountNotifications.test.tsx.snap
src/components/__snapshots__/NotificationRow.test.tsx.snap
src/components/__snapshots__/RepositoryNotifications.test.tsx.snap
src/components/settings/NotificationSettings.tsx
src/utils/helpers.ts

Use sentence case as per https://github.com/gitify-app/gitify/blob/main/CONTRIBUTING.md#design-guidelines

refactor: use sentence case for interaction

---

src/renderer/utils/notifications.ts

Resolves #1567 
Will silently warn and continue when notification enrichment fails, such as when the notification has been deleted

fix: continue if notification enrichment fails

---

config/webpack.config.renderer.base.ts
src/renderer/utils/__snapshots__/emojis.test.ts.snap
src/renderer/utils/emojis.test.ts
src/renderer/utils/emojis.ts

Reduces images assets from ~9.1MB to ~38KB

feat: copy used emoji svgs

---

src/renderer/utils/helpers.ts

It appears that Discussion notification objects now have `subject.url` and `subject.latest_comment.url` populated with an url value.
However, this value returns a 404 causing open interactions for discussions to break and default to the repository url.
Adding a temporary (hopefully) downgrade to revert to our GitHub GraphQL search discussions query to find the matching discussions url

fix: discussions url

---

src/renderer/App.css
src/renderer/components/AccountNotifications.tsx
src/renderer/components/NotificationRow.tsx
src/renderer/components/RepositoryNotifications.tsx
src/renderer/components/__snapshots__/AccountNotifications.test.tsx.snap
src/renderer/components/__snapshots__/NotificationRow.test.tsx.snap
src/renderer/components/__snapshots__/RepositoryNotifications.test.tsx.snap

Add stable scrollbars to prevent horizontal "jumping" when collapsing account / repository notifications

feat: stable scrollbars

---

src/renderer/App.css
src/renderer/components/AccountNotifications.tsx
src/renderer/components/NotificationRow.tsx
src/renderer/components/RepositoryNotifications.tsx
src/renderer/components/__snapshots__/AccountNotifications.test.tsx.snap
src/renderer/components/__snapshots__/NotificationRow.test.tsx.snap
src/renderer/components/__snapshots__/RepositoryNotifications.test.tsx.snap

Reverts gitify-app/gitify#1603

Revert "feat: stable scrollbars"

---

src/renderer/utils/api/__snapshots__/client.test.ts.snap
src/renderer/utils/api/request.ts

fix #1611 
Whether it is `github.com` or GHE Server, set the `Cache-Control: no-cache` header.

fix: set 'Cache-Control: no-cache' for GHE server

---

src/renderer/__mocks__/state-mocks.ts
src/renderer/utils/auth/utils.test.ts
src/renderer/utils/auth/utils.ts
src/renderer/utils/features.test.ts
src/renderer/utils/features.ts

improve robustness of enterprise version parsing

feat: improve version handling robustness

---

src/main/first-run.ts
src/renderer/hooks/useNotifications.ts
src/renderer/utils/api/client.ts
src/renderer/utils/api/request.ts
src/renderer/utils/auth/utils.ts
src/renderer/utils/helpers.ts
src/renderer/utils/notifications.ts
src/renderer/utils/subject.test.ts
src/renderer/utils/subject.ts

Should help future us triage/support user issues better

refactor(logging): improve details in logs

---

package.json
pnpm-lock.yaml

this minor bump causes some uses of octicons, particularly noticeable on Settings and Accounts, to be broken.  
reverting for now to fix `main` and can continue triaging on the new renovate PR

fix(deps): downgrade @primer/octicons-react due to UI regression

---

src/renderer/__mocks__/partial-mocks.ts
src/renderer/__mocks__/state-mocks.ts
src/renderer/routes/Accounts.test.tsx
src/renderer/routes/Accounts.tsx
src/renderer/routes/__snapshots__/Accounts.test.tsx.snap
src/renderer/types.ts
src/renderer/utils/auth/utils.ts

feat(accounts): warn when missing scopes

---

src/main/first-run.ts
src/main/updater.ts
src/main/utils.ts
src/renderer/hooks/useNotifications.test.ts
src/renderer/hooks/useNotifications.ts
src/renderer/routes/Accounts.tsx
src/renderer/routes/Login.tsx
src/renderer/routes/LoginWithOAuthApp.tsx
src/renderer/routes/LoginWithPersonalAccessToken.tsx
src/renderer/utils/api/client.test.ts
src/renderer/utils/api/client.ts
src/renderer/utils/api/request.ts
src/renderer/utils/auth/migration.ts
src/renderer/utils/auth/utils.ts
src/renderer/utils/helpers.test.ts
src/renderer/utils/helpers.ts
src/renderer/utils/logger.test.ts
src/renderer/utils/logger.ts
src/renderer/utils/notifications.ts
src/renderer/utils/subject.test.ts
src/renderer/utils/subject.ts
src/shared/logger.test.ts
src/shared/logger.ts

Thanks @bmulholland https://github.com/gitify-app/gitify/pull/1681#issuecomment-2564054261

refactor(shared): create `electron-log` wrapper

---

src/renderer/App.tsx
src/renderer/components/Sidebar.tsx
src/renderer/components/__snapshots__/Sidebar.test.tsx.snap

feat: shrink sidebar width

---

src/renderer/components/fields/RadioGroup.tsx

We don't use the RadioGroup tooltip option

refactor: remove unused tooltip option

---

src/renderer/routes/Filters.tsx

"Clear Filters" button was not unchecking selected filters because of a reference between `settings` and `defaultSettings`. i.e., whenever filters changed, the filter reasons in the `defaultFilters` object also mutated, which is not desirable.
Using the spread operator to get selected filters fixes this issue.
**Video of bug:**
https://github.com/user-attachments/assets/1719e109-ca10-4c29-afe0-7a3d5337660e

fix: prevent default filters from getting overwritten

---

src/renderer/components/notifications/NotificationHeader.test.tsx
src/renderer/components/notifications/NotificationHeader.tsx
src/renderer/components/notifications/NotificationRow.tsx
src/renderer/components/notifications/__snapshots__/AccountNotifications.test.tsx.snap
src/renderer/components/notifications/__snapshots__/NotificationHeader.test.tsx.snap
src/renderer/components/notifications/__snapshots__/NotificationRow.test.tsx.snap

Matches the UX of the GitHub Mobile (Android) experience

feat: notification number relo for groupByDate mode

---

src/renderer/components/avatars/AvatarWithFallback.test.tsx
src/renderer/components/avatars/AvatarWithFallback.tsx
src/renderer/components/avatars/__snapshots__/AvatarWithFallback.test.tsx.snap
src/renderer/components/fields/RadioGroup.test.tsx
src/renderer/components/notifications/AccountNotifications.tsx
src/renderer/components/notifications/NotificationFooter.tsx
src/renderer/components/notifications/NotificationHeader.tsx
src/renderer/components/notifications/RepositoryNotifications.tsx
src/renderer/components/notifications/__snapshots__/AccountNotifications.test.tsx.snap
src/renderer/components/notifications/__snapshots__/NotificationFooter.test.tsx.snap
src/renderer/components/notifications/__snapshots__/NotificationHeader.test.tsx.snap
src/renderer/components/notifications/__snapshots__/NotificationRow.test.tsx.snap
src/renderer/components/notifications/__snapshots__/RepositoryNotifications.test.tsx.snap
src/renderer/routes/Accounts.tsx
src/renderer/routes/__snapshots__/Accounts.test.tsx.snap

New avatar component that handles img error loading with fallback icons
| 😄    | 😅 |
| -------- | ------- |
| ![2025-01-23T12-19-22 379Z-Gitify-screenshot](https://github.com/user-attachments/assets/5f52d25b-c368-4d71-acdc-a535fd89728e) |  ![2025-01-23T12-18-50 648Z-Gitify-screenshot](https://github.com/user-attachments/assets/31da54f6-137d-4475-b01a-1c56d44fd3fc)  |
Closes #1224 (or at least provides a "better" option than completely broken images)

feat: avatar with fallback icons component

---

src/renderer/__mocks__/state-mocks.ts
src/renderer/components/notifications/NotificationRow.tsx
src/renderer/components/notifications/__snapshots__/AccountNotifications.test.tsx.snap
src/renderer/components/notifications/__snapshots__/NotificationRow.test.tsx.snap
src/renderer/components/settings/AppearanceSettings.test.tsx
src/renderer/components/settings/AppearanceSettings.tsx
src/renderer/context/App.tsx
src/renderer/routes/__snapshots__/Settings.test.tsx.snap
src/renderer/types.ts

Closes #1370 
| Truncate | Wrap |
| --- | --- |
|![2025-01-26T12-34-09 673Z-Gitify-screenshot](https://github.com/user-attachments/assets/c4b45484-831a-4053-9a1c-bf96381ec276) | ![2025-01-26T12-34-17 657Z-Gitify-screenshot](https://github.com/user-attachments/assets/8457c8ee-ad71-4086-9e08-f25c291a5304) |

feat: user setting to wrap notification titles

---

src/renderer/components/notifications/AccountNotifications.tsx
src/renderer/components/notifications/NotificationRow.tsx
src/renderer/components/notifications/RepositoryNotifications.tsx
src/renderer/components/primitives/HoverGroup.test.tsx
src/renderer/components/primitives/HoverGroup.tsx
src/renderer/components/primitives/__snapshots__/HoverGroup.test.tsx.snap

classic CSS "fun"... 
The dynamic tailwind group-hover background class, for some unknown reason, wasn't reliably rendering.
This change feels a bit odd, but makes the app behave predictably

fix: hover group background color

---

src/renderer/components/settings/AppearanceSettings.tsx
src/renderer/routes/__snapshots__/Settings.test.tsx.snap

Clean up these dependent appearance settings that require `detailed notifications` data in order to function.
| Disabled | Enabled |
| --- | --- | 
| ![2025-01-28T22-15-10 678Z-Gitify-screenshot](https://github.com/user-attachments/assets/a22401ad-2d10-4c57-872a-c5ccd26d3952) | ![2025-01-28T22-15-16 257Z-Gitify-screenshot](https://github.com/user-attachments/assets/cb467e46-f49d-4fa8-877d-3b8631f9eb42) |

refactor: nest detailed notification sub-settings

---

src/renderer/components/avatars/AvatarWithFallback.tsx
src/renderer/components/avatars/__snapshots__/AvatarWithFallback.test.tsx.snap
src/renderer/components/notifications/__snapshots__/AccountNotifications.test.tsx.snap
src/renderer/components/notifications/__snapshots__/NotificationFooter.test.tsx.snap
src/renderer/components/notifications/__snapshots__/NotificationHeader.test.tsx.snap
src/renderer/components/notifications/__snapshots__/NotificationRow.test.tsx.snap
src/renderer/components/notifications/__snapshots__/RepositoryNotifications.test.tsx.snap
src/renderer/routes/Accounts.tsx
src/renderer/routes/__snapshots__/Accounts.test.tsx.snap

Ensure lengthy avatar names (repository, username, etc) are appropriately truncated

feat: truncate long avatar names

---

package.json
src/main/main.ts

Taking a guess that future us may like to separate the production app protocol from the development protocol

feat: gitify dev protocol

---

.github/workflows/test.yml
README.md
renovate.json
sonar-project.properties

My experience with Coveralls has been pretty ordinary when trying to review coverage reports. 
Switching to SonarQube Cloud which will provide coverage feedback along plus other static analysis rules

feat: sonarqube setup

---

src/renderer/components/avatars/AvatarWithFallback.tsx
src/renderer/components/fields/Checkbox.tsx
src/renderer/components/metrics/MetricPill.tsx
src/renderer/components/notifications/NotificationRow.tsx
src/renderer/typesGitHub.ts
src/renderer/utils/auth/utils.test.ts
src/renderer/utils/auth/utils.ts
src/renderer/utils/constants.ts

Continuation of fixing sonar issues

fix: further sonar issues

---

src/renderer/routes/Accounts.tsx
src/renderer/routes/LoginWithPersonalAccessToken.tsx
src/renderer/routes/__snapshots__/Accounts.test.tsx.snap
src/renderer/utils/auth/utils.ts
src/renderer/utils/constants.ts

Closes https://github.com/gitify-app/gitify/issues/1830
Supported by https://github.com/gitify-app/website/pull/344

feat: public_repo alternate scopes

---

src/renderer/components/filters/UserHandleFilter.tsx

Add filter tokens on input blur

feat: add handle filter tokens on blur

---

src/renderer/__mocks__/state-mocks.ts
src/renderer/components/filters/StateFilter.tsx
src/renderer/components/filters/SubjectTypeFilter.test.tsx
src/renderer/components/filters/SubjectTypeFilter.tsx
src/renderer/components/filters/__snapshots__/StateFilter.test.tsx.snap
src/renderer/components/filters/__snapshots__/SubjectTypeFilter.test.tsx.snap
src/renderer/context/App.tsx
src/renderer/routes/Filters.tsx
src/renderer/routes/__snapshots__/Filters.test.tsx.snap
src/renderer/types.ts
src/renderer/utils/notifications/filters/filter.test.ts
src/renderer/utils/notifications/filters/filter.ts
src/renderer/utils/notifications/filters/state.ts
src/renderer/utils/notifications/filters/subjectType.ts

I figured while we're updating the `Filters` module, why not add the ability to filter by notification type

feat: filter by notification type

---

package.json
pnpm-lock.yaml
scripts/afterSign.js

Based on my experience releasing the latest version of Atlassify - https://github.com/setchy/atlassify/releases/tag/v1.15.0

fix: notarize process

---

src/renderer/components/settings/AppearanceSettings.tsx
src/renderer/routes/__snapshots__/Settings.test.tsx.snap

Use the https://primer.style/octicons/ Zoom In and Zoom Out icons, along with Sync (for reset)
| Before | After | 
| --- | --- |
| ![2025-04-23T15-51-59 228Z-Gitify-screenshot](https://github.com/user-attachments/assets/cafa498a-eda3-4b54-82a6-8d5ddd278998) | ![2025-04-23T15-50-44 019Z-Gitify-screenshot](https://github.com/user-attachments/assets/4719c8c0-bbb9-4c1f-a4fe-2600de6f4e85) |

refactor: zoom in and out icons

---

renovate.json

Fetch changelog notes for https://github.com/discord/twemoji from https://github.com/jdecked/twemoji

build: configure twemoji changelog to be upstream fork

---

src/renderer/utils/api/client.ts
src/renderer/utils/api/graphql/discussions.ts

GitHub GraphQL API changed to require at least one pagination argument for `labels`

fix(discussions): fetch labels

---

package.json
pnpm-lock.yaml
src/renderer/App.css

Simplify our `@primer/css` use

refactor: use `@primer/css` directly

---

.vscode/settings.json
src/renderer/__mocks__/state-mocks.ts
src/renderer/components/filters/OrganizationFilter.test.tsx
src/renderer/components/filters/OrganizationFilter.tsx
src/renderer/context/App.tsx
src/renderer/routes/Filters.tsx
src/renderer/routes/__snapshots__/Filters.test.tsx.snap
src/renderer/types.ts
src/renderer/utils/notifications/filters/filter.test.ts
src/renderer/utils/notifications/filters/filter.ts
src/renderer/utils/notifications/filters/index.ts
src/renderer/utils/notifications/filters/organizations.test.ts
src/renderer/utils/notifications/filters/organizations.ts

Adding an Organization filter (just like the Handle filter)

feat: added the organization filter

---

package.json
pnpm-lock.yaml
src/main/index.ts
src/main/updater.test.ts
src/main/updater.ts
src/shared/constants.ts

This enhancement drops `update-electron-app` and uses `electron-updater` directly.
This should mean that Linux and Windows users will now received automated (scheduled) update support 🚀

feat: auto updates for all platforms

---

src/renderer/context/App.test.tsx
src/renderer/context/App.tsx

thanks for finding this @vallieres 🙇

fix(login): pat

---

src/main/utils.ts
src/renderer/components/filters/TokenSearchInput.tsx
src/renderer/components/metrics/MetricPill.tsx
src/renderer/components/primitives/Title.tsx
src/renderer/components/settings/AppearanceSettings.tsx
src/renderer/routes/__snapshots__/LoginWithOAuthApp.test.tsx.snap
src/renderer/routes/__snapshots__/LoginWithPersonalAccessToken.test.tsx.snap
src/renderer/routes/__snapshots__/Settings.test.tsx.snap
src/renderer/utils/helpers.ts
src/renderer/utils/notifications/handlers/pullRequest.ts
src/renderer/utils/notifications/handlers/utils.ts
src/renderer/utils/notifications/native.ts
src/renderer/utils/notifications/notifications.ts
src/renderer/utils/notifications/remove.ts
src/renderer/utils/zoom.ts

fix a collection of sonar issue

refactor: fix sonarlint issues
