- README.md
> Include link to download in the README.md

- src/less/style.less
> Ui - Improve :hover of notification

- index.html
> Disable zoom in BrowserWindow

- package.json
> Update Electron 0.27.2

- src/js/components/repository.js
- src/less/style.less
Ellipsize Organisation or Repository name if they are longer than 50% of the title area.
> Ellipsize repo names

- package.json
> Update electron 0.28.1

- src/less/style.less
> Fix search input - padding

- package.json
> Add ulimit to npm run build

- package.json
Electron 0.30.1 - StatusItemView
https://github.com/atom/electron/pull/2232
** Update: Electron 0.30.2 - Fixes tray icon **
> Update electron to 0.30.2

- README.md
- package.json
- src/js/__tests__/components/notification.js
- src/js/__tests__/components/notifications.js
- src/js/__tests__/components/repository.js
- src/js/__tests__/stores/notifications.js
- src/js/actions/actions.js
- src/js/components/notification.js
- src/js/components/notifications.js
- src/js/components/repository.js
- src/js/stores/notifications.js
- src/less/style.less
> Animation for marking notification as read

- package.json
- src/js/components/login.js
> Bug: Authenticate with GitHub

- main.js
- package.json
- scripts/codesign.bash
> Auto Update

- index.html
> Allow mousewheel scrolling

- src/js/components/navigation.js
- src/js/components/notification.js
> Tooltips for Icons

- main.js
> Default Position for BrowserWindow

- src/js/__tests__/components/notification.js
- src/js/__tests__/components/repository.js
- src/js/components/notification.js
- src/js/components/settings.js
- src/js/stores/settings.js
- src/less/style.less
> Settings - "On Click, Mark as Read"

- src/js/__tests__/components/navigation.js
- src/js/app.js
- src/js/components/navigation.js
> Close search on logout

- README.md
> Add Homebrew Cask to README

- src/js/store/configureStore.js
> Fix settings issue

- README.md
- auto_updater.json
- main.js
- package.json
> Release 1.0.0

- gulpfile.js
- src/js/__tests__/actions/index.js
- src/js/__tests__/components/navigation.js
- src/js/__tests__/middleware/notifications.js
- src/js/__tests__/utils/helpers.js
- src/js/actions/index.js
- src/js/components/navigation.js
- src/js/middleware/notifications.js
- src/js/utils/helpers.js
- src/scss/app.scss
> [202] Green icon if notifications

- src/js/__tests__/utils/helpers.js
- src/js/utils/helpers.js
> [167] Release notifications

- src/js/__tests__/reducers/notifications.js
- src/js/reducers/notifications.js
> Fix App Crashing on Fetch Notifications Failure

- README.md
> Add FAQ entry about organisation permissions

- .sass-lint.yml
- main.js
- package.json
- src/js/__tests__/components/loading.js
- src/js/__tests__/components/notifications.js
- src/js/__tests__/components/repository.js
- src/js/__tests__/components/sidebar.js
- src/js/components/loading.js
- src/js/components/notifications.js
- src/js/components/repository.js
- src/js/components/sidebar.js
- src/js/containers/app.js
- src/scss/app.scss
> [v2] Sidebar

- src/js/utils/helpers.js
More at https://github.com/electron/electron/issues/8838
Closes #295.
> Fix login issue

- auto_updater.json
- package.json
> Bump 2.0.1

- main.js
- src/js/__mocks__/electron.js
- src/js/utils/notifications.js
> Tray Icon, toggle gitify on click

- README.md
- auto_updater.json
- package.json
> Release 2.0.2

- .github/workflows/main.yml
See more at https://github.community/t5/GitHub-Actions/PR-from-fork-does-not-show-actions-even-though-actions-start-on/td-p/39895
> Run GitHub actions on PRs from forks

- .github/workflows/release.yml
* Setup release workflow
* Pass GH Token & publish with onTagOrDraft
> Setup Release GitHub Action (#376)

- src/js/utils/notifications.ts
"You have got 5 notifications" -> "You have 5 notifications"
> Grammar fix in notification message

- src/js/components/__snapshots__/account-notifications.test.tsx.snap
- src/js/components/__snapshots__/all-read.test.tsx.snap
- src/js/components/__snapshots__/notification.test.tsx.snap
- src/js/components/__snapshots__/oops.test.tsx.snap
- src/js/components/__snapshots__/repository.test.tsx.snap
- src/js/components/__snapshots__/sidebar.test.tsx.snap
- src/js/components/account-notifications.tsx
- src/js/components/all-read.tsx
- src/js/components/fields/input.tsx
- src/js/components/notification.tsx
- src/js/components/oops.tsx
- src/js/components/repository.tsx
- src/js/components/sidebar.tsx
- src/js/components/ui/checkbox.tsx
- src/js/routes/__snapshots__/enterprise-login.test.tsx.snap
- src/js/routes/__snapshots__/login.test.tsx.snap
- src/js/routes/__snapshots__/notifications.test.tsx.snap
- src/js/routes/__snapshots__/settings.test.tsx.snap
- src/js/routes/enterprise-login.tsx
- src/js/routes/login.tsx
- src/js/routes/notifications.tsx
- src/js/routes/settings.tsx
- tailwind.config.js
> feat: Hello "Dark Mode"

- .github/workflows/pr-title-validator.yml
> feat: add pr title validator

- .npmrc
> fix: pnpm config for `electron-builder`

- package.json
- pnpm-lock.yaml
- src/components/AllRead.test.tsx
- src/components/NotificationRow.test.tsx
- src/components/Oops.test.tsx
- src/components/Repository.test.tsx
- src/components/Sidebar.test.tsx
- src/components/test-utils.ts
- src/context/App.test.tsx
- src/routes/Login.test.tsx
- src/routes/LoginEnterprise.test.tsx
- src/utils/auth.test.ts
- src/utils/comms.test.ts
- src/utils/notifications.test.ts
- tsconfig.json
Step one done :). I suspect this is the hardest one, and from here to 29 will be easy.
> chore(deps): Upgrade to Jest v27

- .github/workflows/trigger-homebrew.yml
I was a bit wary of using an external dependency here, but it makes it easier than dealing with the CLI directly, and since this is just a wrapper we should be fine.
> feat: automate cask bump

- .husky/pre-commit
- package.json
- pnpm-lock.yaml
> feat: add husky to apply prettier and run tests

- package.json
- pnpm-lock.yaml
It seems that we're only using the GH action, not the package, so we should be free to remove this.
> deps: remove coveralls

- src/utils/helpers.test.ts
- src/utils/helpers.ts
Closes https://github.com/gitify-app/gitify/issues/670
> feat: link to release tag

- first-run.js
creates the folder for the firstRun file if it does not exist https://github.com/gitify-app/gitify/issues/679
> feat: create FirstRun directory if missing 

- src/typesGithub.ts
- src/utils/github-api.test.ts
- src/utils/github-api.ts
> feat: add support for `WorkflowRun` subject

- jest.config.js
Add `collectCoverage: true` to jest configuration
> build(jest): enable coverage by default

- src/components/AllRead.test.tsx
- src/components/Loading.test.tsx
- src/components/Logo.test.tsx
- src/components/NotificationRow.test.tsx
- src/components/Oops.test.tsx
- src/components/__snapshots__/AllRead.test.tsx.snap
- src/components/__snapshots__/Logo.test.tsx.snap
- src/components/__snapshots__/NotificationRow.test.tsx.snap
- src/components/__snapshots__/Oops.test.tsx.snap
- src/routes/LoginEnterprise.test.tsx
- src/routes/LoginWithToken.test.tsx
- src/routes/Notifications.test.tsx
- src/routes/__snapshots__/LoginEnterprise.test.tsx.snap
- src/routes/__snapshots__/LoginWithToken.test.tsx.snap
- src/routes/__snapshots__/Notifications.test.tsx.snap
- src/utils/__snapshots__/github-api.test.ts.snap
- src/utils/appearance.test.ts
- src/utils/github-api.test.ts
- src/utils/remove-notifications.test.ts
- src/utils/subject.test.ts
Update tests to ensure the test suite name matches that of the code under test
> refactor(jest): align test suite names to match code under test

- src/__mocks__/mockedData.ts
- src/typesGithub.ts
- src/utils/helpers.ts
Align types to match GitHub GraphQL SDL and use fragment to ensure comments and replies fields are always in-sync
> refactor(discussions): align type names to SDL and use fragment

- src/components/NotificationRow.tsx
- src/components/Repository.tsx
- src/components/__snapshots__/NotificationRow.test.tsx.snap
- src/components/__snapshots__/Repository.test.tsx.snap
Add cursor pointer to Repository and Notification interactive elements
> feat: add cursor pointer to interactive elements

- package.json
Closes https://github.com/gitify-app/gitify/issues/413
> feat: add linux rpm support

- src/components/Oops.tsx
thank you Mr Biome for picking this up
> fix: update oops useMemo

- src/routes/Settings.tsx
- src/routes/__snapshots__/Settings.test.tsx.snap
Fix a regression from address biome errors/warnings
**Regression**
**Resolved**
> fix: release version font size

- src/components/AccountNotifications.test.tsx
- src/components/fields/RadioGroup.test.tsx
> refactor: fix typo

- .vscode/extensions.json
https://tailwindcss.com/docs/editor-setup
> build(vscode): add tailwind extension

- src/routes/Settings.tsx
- src/routes/__snapshots__/Settings.test.tsx.snap
> fix: remove erroneous helpText

- renovate.json
Update Renovate configuration to
- favor preset configurations
- increase frequency from monthly to weekly since we're in an active development/management phase
> build(renovate): use presets and increase frequency

- src/typesGithub.ts
- src/utils/subject.test.ts
- src/utils/subject.ts
> feat(subject): support enriched commit notification details

- src/__mocks__/partial-mocks.ts
- src/utils/subject.test.ts
- src/utils/subject.ts
Refactor the subject test suite to
* more succinct and realistic mocks
* improve assertions to cover full user object
* add tests for checksuite and workflow subject
> test(utils/subject): improve mocks and test cases

- renovate.json
For automated `$schema` version update goodness
> build(renovate): use biome versions preset

- src/routes/Settings.tsx
Replace uses of promise -> then with async -> await
> refactor(settings): use async await

- src/utils/constants.ts
- src/utils/helpers.ts
> refactor: return static github api path

- src/components/NotificationRow.test.tsx
- src/typesGitHub.ts
Use a type instead of a string for User types
> refactor: add user type

- src/components/NotificationRow.test.tsx
> test(notification): add coverage for keyDown event

- package.json
- pnpm-lock.yaml
- src/__mocks__/mockedData.ts
- src/typesGitHub.ts
- src/utils/api/client.ts
- src/utils/api/graphql/discussions.ts
- src/utils/api/utils.test.ts
- src/utils/api/utils.ts
- src/utils/constants.ts
- src/utils/helpers.test.ts
- src/utils/helpers.ts
Extract the discussions GraphQL API call into our api/client, along with the GQL operation document and supporting helpers
> refactor: extract discussions api calls into client

- package.json
> chore: prepare 5.5.0 release

- main.js
Can't quite tell _why_ these were async 🤷‍♂️
> refactor: remove async from ipc handlers

- src/__mocks__/mockedData.ts
- src/components/NotificationRow.test.tsx
- src/components/NotificationRow.tsx
- src/components/__snapshots__/NotificationRow.test.tsx.snap
- src/typesGitHub.ts
- src/utils/api/graphql/discussions.ts
- src/utils/subject.test.ts
- src/utils/subject.ts
Applies to Issues, Pull Requests and Discussions
> feat: add comment count icon

- .github/workflows/on-tag.yml
Set `GITIFY_VERSION` environment variable correctly
> build: set version

- src/components/Repository.test.tsx
- src/components/Sidebar.test.tsx
- src/routes/Login.test.tsx
- src/routes/Login.tsx
- src/routes/LoginWithOAuthApp.test.tsx
- src/routes/LoginWithOAuthApp.tsx
- src/routes/Settings.test.tsx
replace require with import statements
> refactor: update import statements

- src/components/AccountNotifications.tsx
- src/components/__snapshots__/AccountNotifications.test.tsx.snap
> fix: account name header height

- src/types.ts
> refactor: user's name can be null

- src/routes/Notifications.test.tsx
- src/routes/__snapshots__/Notifications.test.tsx.snap
Fixing these that showed when running tests.
> fix: notification component mocks

- src/context/App.tsx
> refactor: theme casting not required

- src/components/Repository.test.tsx
- src/components/Repository.tsx
- src/context/App.test.tsx
- src/context/App.tsx
- src/hooks/useNotifications.test.ts
- src/hooks/useNotifications.ts
rename 
- `markRepoNotifications` to `markRepoNotificationsRead`
- `markRepoNotificationsWithAccounts` to `markRepoNotificationsReadWithAccounts`
> refactor: rename to markRepoNotificationsRead

- main.js
Add right-click context menu with `Quit` app option
> feat: tray context menu

- index.html
To me these styles look to be unused / orphaned
> refactor: remove unused styles

- src/components/__snapshots__/NotificationRow.test.tsx.snap
- src/components/buttons/PillButton.tsx
- src/components/buttons/__snapshots__/PillButton.test.tsx.snap
Before
After
Note: After includes fixes in other PRs
> fix: release notifications pill

- src/components/__snapshots__/NotificationRow.test.tsx.snap
- src/components/buttons/PillButton.tsx
- src/components/buttons/__snapshots__/PillButton.test.tsx.snap
- tailwind.config.js
> refactor: rename custom text size to xxs

- src/components/fields/RadioGroup.tsx
- src/components/fields/__snapshots__/RadioGroup.test.tsx.snap
- src/routes/__snapshots__/Settings.test.tsx.snap
> fix: radio buttons alignment

- .husky/pre-commit
see https://github.com/gitify-app/gitify/pull/1357#issuecomment-2221751031
> build: revert to use pnpx

- src/components/buttons/Button.tsx
- src/components/fields/Checkbox.tsx
- src/components/fields/RadioGroup.tsx
- src/components/fields/__snapshots__/Checkbox.test.tsx.snap
- src/components/fields/__snapshots__/RadioGroup.test.tsx.snap
- src/components/settings/AppearanceSettings.tsx
- src/routes/__snapshots__/Filters.test.tsx.snap
- src/routes/__snapshots__/Settings.test.tsx.snap
| Before | After |
| ---- | ---- |
| <img width="501" alt="Screenshot 2024-07-11 at 8 31 08 AM" src="https://github.com/gitify-app/gitify/assets/386277/b7d0be23-c84c-4d46-b79a-217ee1938130"> | <img width="501" alt="Screenshot 2024-07-11 at 8 25 43 AM" src="https://github.com/gitify-app/gitify/assets/386277/145aa5ae-eb63-4824-8bcc-0d167113b179"> |
> refactor: slim down zoom controls

- src/components/fields/RadioGroup.tsx
In preparation for #1366 documentation against #1376 `SystemSettings`
> feat: add tooltip support to radio group

- src/components/NotificationRow.tsx
- src/components/RepositoryNotifications.tsx
- src/components/__snapshots__/AccountNotifications.test.tsx.snap
- src/components/__snapshots__/NotificationRow.test.tsx.snap
- src/components/__snapshots__/RepositoryNotifications.test.tsx.snap
Simplification and fix of our overflow/truncate behavior for repository and notification titles
> fix: overflow ellipsis

- src/utils/comms.test.ts
- src/utils/comms.ts
A better approach that preventing `file:///` links
> refactor: only open https external links

- src/electron/main.js
Add keyboard accelerators for 
* Reload
* Toggle Dev Tools
* Quit
> feat: add accelerator shortcuts

- package.json
https://github.com/gitify-app/gitify/milestone/26?closed=1
> build: prepare `v5.12.0` release

- src/routes/LoginWithOAuthApp.tsx
- src/routes/LoginWithPersonalAccessToken.tsx
- src/routes/__snapshots__/LoginWithOAuthApp.test.tsx.snap
- src/routes/__snapshots__/LoginWithPersonalAccessToken.test.tsx.snap
- Move `Generate a PAT` above `Token` input
- Add size to Button components
- Add Button text (Docs, Login) to OAuth view
> refactor: login pages ui

- .github/ISSUE_TEMPLATE/bug_report.yml
- package.json
https://github.com/gitify-app/gitify/releases/tag/v5.13.1
> build: prepare `v5.13.1` release

- src/components/AccountNotifications.tsx
- src/components/__snapshots__/AccountNotifications.test.tsx.snap
event propagation was playing up when clicking on the header issues and PR quick links.
Also made account avatar part of the open profile button
> fix: account header quick links

- .github/ISSUE_TEMPLATE/bug_report.yml
- package.json
https://github.com/gitify-app/gitify/releases/tag/v5.14.0
> build: prepare `v5.14.0` release

- package.json
- scripts/remove-unused-locales.js
> build: remove unused language locale resources

- .github/ISSUE_TEMPLATE/bug_report.yml
- CONTRIBUTING.md
- jest.config.ts
- package.json
- scripts/notarize.js
- scripts/remove-unused-locales.js
https://github.com/gitify-app/gitify/milestone/31
> build: prepare `v5.15.0` release

- package.json
https://github.com/gitify-app/gitify/milestone/32
> build: prepare `v5.16.0` release

- package.json
- src/renderer/utils/emojis.ts
https://github.com/gitify-app/gitify/milestone/34
> build: prepare `v5.16.1` release

- package.json
https://github.com/gitify-app/gitify/milestone/33
> build: prepare `v5.16.2` release

- src/renderer/typesGitHub.ts
- src/renderer/utils/api/client.ts
- src/renderer/utils/api/graphql/discussions.ts
- src/renderer/utils/helpers.test.ts
- src/renderer/utils/helpers.ts
> fix(discussions): answered discussions only available in GHES 3.12 or higher

- package.json
https://github.com/gitify-app/gitify/milestone/35
> build: prepare `v5.17.0` release

- src/main/main.ts
Avoids linux users getting daily log entries
> feat: limit auto updater

- src/renderer/utils/auth/utils.test.ts
- src/renderer/utils/auth/utils.ts
Incorrect URL for GitHub app method
> fix: github app url

- src/renderer/App.tsx
Prevent horizontal scrollbar briefly appearing on notification transition animation
> fix: x overflow always hidden

- src/renderer/components/notifications/NotificationFooter.tsx
- src/renderer/components/notifications/__snapshots__/AccountNotifications.test.tsx.snap
- src/renderer/components/notifications/__snapshots__/NotificationFooter.test.tsx.snap
- src/renderer/components/notifications/__snapshots__/NotificationRow.test.tsx.snap
- src/renderer/utils/helpers.test.ts
- src/renderer/utils/helpers.ts
> feat: adopt RelativeTime primer component

- src/renderer/context/App.tsx
Working through the feedback from Sonar to address items that it's highlighted
> fix: issues identified by sonar

- src/renderer/components/AllRead.tsx
- src/renderer/components/Oops.tsx
1. https://sonarcloud.io/project/security_hotspots?id=gitify-app_gitify&hotspots=AZS1NAVctoWZECl0K8uX
2. https://sonarcloud.io/project/security_hotspots?id=gitify-app_gitify&hotspots=AZS1NAVOtoWZECl0K8uU
> refactor: suppress math.random sonar warnings

- src/renderer/routes/Login.tsx
https://sonarcloud.io/project/issues?open=AZTc_2eDZA4-S-buMQ-0&id=gitify-app_gitify
> refactor: resolve sonar feedback re login fn

- src/renderer/utils/api/utils.ts
- src/renderer/utils/subject.ts
1. https://sonarcloud.io/project/security_hotspots?id=gitify-app_gitify&hotspots=AZS1NAVvtoWZECl0K8uo
2. https://sonarcloud.io/project/security_hotspots?id=gitify-app_gitify&hotspots=AZS1NAXLtoWZECl0K8u5
> refactor: resolve sonar feedback on regex patterns

- package.json
https://github.com/gitify-app/gitify/milestone/38
> build: prepare `v6.1.0` release

- .github/workflows/build.yml
- .github/workflows/publish.yml
- package.json
- scripts/notarize.js
https://github.com/gitify-app/gitify/milestone/39
> build: prepare `v6.2.0` release

- package.json
https://github.com/gitify-app/gitify/milestone/40
> build: prepare `v6.3.0` release

- package.json
- sonar-project.properties
https://github.com/gitify-app/gitify/milestone/43
> build: prepare `v6.4.1` release

- package.json
- sonar-project.properties
https://github.com/gitify-app/gitify/milestone/45
> build: prepare `v6.7.0` release

- package.json
- sonar-project.properties
https://github.com/gitify-app/gitify/milestone/46
> build: prepare `v6.8.0` release
